# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 451b0dc0b4b09ed000cc2f1e3281fcfa34f1b75a1808aba9492a16ef7822a598832dc9a9253394fe49d294dbc2c965d25ae373956389386315655182406c3d92

test:
  secret_key_base: 9ca93da07f5afe20a4d6f0c232ef550ed31906ec4493fbee935735d5b89df514751c9a32f03f31debac4f5dee253aeaab173e2c3be7f1e582086f3838cf0513f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
